#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v12
# autospec commit: 381dfd8
#
Name     : coturn
Version  : 4.6.2
Release  : 10
URL      : https://github.com/coturn/coturn/archive/4.6.2/coturn-4.6.2.tar.gz
Source0  : https://github.com/coturn/coturn/archive/4.6.2/coturn-4.6.2.tar.gz
Source1  : turnserver.service
Summary  : The TURN Server is a VoIP media traffic NAT traversal server and gateway
Group    : Development/Tools
License  : BSD-3-Clause
Requires: coturn-bin = %{version}-%{release}
Requires: coturn-data = %{version}-%{release}
Requires: coturn-license = %{version}-%{release}
Requires: coturn-man = %{version}-%{release}
Requires: coturn-services = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libevent)
BuildRequires : pkgconfig(systemd)
BuildRequires : postgresql-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Fix-build.patch

%description
The TURN Server is a VoIP media traffic NAT traversal server and gateway. It
can be used as a general-purpose network traffic TURN server/gateway, too.

This implementation also includes some extra features. Supported RFCs:

TURN specs:
- RFC 5766 - base TURN specs
- RFC 6062 - TCP relaying TURN extension
- RFC 6156 - IPv6 extension for TURN
- Experimental DTLS support as client protocol.

STUN specs:
- RFC 3489 - "classic" STUN
- RFC 5389 - base "new" STUN specs
- RFC 5769 - test vectors for STUN protocol testing
- RFC 5780 - NAT behavior discovery support

The implementation fully supports the following client-to-TURN-server protocols:
- UDP (per RFC 5766)
- TCP (per RFC 5766 and RFC 6062)
- TLS (per RFC 5766 and RFC 6062); TLS1.0/TLS1.1/TLS1.2
- DTLS (experimental non-standard feature)

Supported relay protocols:
- UDP (per RFC 5766)
- TCP (per RFC 6062)

Supported user databases (for user repository, with passwords or keys, if
authentication is required):
- SQLite
- MySQL
- PostgreSQL
- Redis

Redis can also be used for status and statistics storage and notification.

Supported TURN authentication mechanisms:
- long-term
- TURN REST API (a modification of the long-term mechanism, for time-limited
  secret-based authentication, for WebRTC applications)

The load balancing can be implemented with the following tools (either one or a
combination of them):
- network load-balancer server
- DNS-based load balancing
- built-in ALTERNATE-SERVER mechanism.

%package bin
Summary: bin components for the coturn package.
Group: Binaries
Requires: coturn-data = %{version}-%{release}
Requires: coturn-license = %{version}-%{release}
Requires: coturn-services = %{version}-%{release}

%description bin
bin components for the coturn package.


%package data
Summary: data components for the coturn package.
Group: Data

%description data
data components for the coturn package.


%package dev
Summary: dev components for the coturn package.
Group: Development
Requires: coturn-bin = %{version}-%{release}
Requires: coturn-data = %{version}-%{release}
Provides: coturn-devel = %{version}-%{release}
Requires: coturn = %{version}-%{release}

%description dev
dev components for the coturn package.


%package doc
Summary: doc components for the coturn package.
Group: Documentation
Requires: coturn-man = %{version}-%{release}

%description doc
doc components for the coturn package.


%package license
Summary: license components for the coturn package.
Group: Default

%description license
license components for the coturn package.


%package man
Summary: man components for the coturn package.
Group: Default

%description man
man components for the coturn package.


%package services
Summary: services components for the coturn package.
Group: Systemd services
Requires: systemd

%description services
services components for the coturn package.


%prep
%setup -q -n coturn-4.6.2
cd %{_builddir}/coturn-4.6.2
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719423128
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719423128
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/coturn
cp %{_builddir}/coturn-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/coturn/44edc3a7a30e912f10454aee90d312a5d0d7fa24 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/turnserver.service
## install_append content
install -D -m 0644 %{buildroot}/usr/etc/turnserver.conf.default %{buildroot}/usr/share/coturn/turnserver.conf.default
rm %{buildroot}/usr/etc/turnserver.conf.default
rmdir %{buildroot}/usr/etc
mv %{buildroot}/usr/doc %{buildroot}/usr/share/doc
mv %{buildroot}/usr/man %{buildroot}/usr/share/man
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/turnadmin
/usr/bin/turnserver
/usr/bin/turnutils_natdiscovery
/usr/bin/turnutils_oauth
/usr/bin/turnutils_peer
/usr/bin/turnutils_rfc5769check
/usr/bin/turnutils_stunclient
/usr/bin/turnutils_uclient

%files data
%defattr(-,root,root,-)
/usr/share/coturn/turnserver.conf.default
/usr/share/examples/ca/CA.pl.diff
/usr/share/examples/ca/CA/cacert.pem
/usr/share/examples/ca/CA/careq.pem
/usr/share/examples/ca/CA/crlnumber
/usr/share/examples/ca/CA/index.txt
/usr/share/examples/ca/CA/index.txt.attr
/usr/share/examples/ca/CA/index.txt.attr.old
/usr/share/examples/ca/CA/index.txt.old
/usr/share/examples/ca/CA/newcerts/4C9BEC95D121491D5D65A71A614667DD42186546.pem
/usr/share/examples/ca/CA/newcerts/4C9BEC95D121491D5D65A71A614667DD42186547.pem
/usr/share/examples/ca/CA/newcerts/4C9BEC95D121491D5D65A71A614667DD42186548.pem
/usr/share/examples/ca/CA/private/cakey.pem
/usr/share/examples/ca/CA/serial
/usr/share/examples/ca/CA/serial.old
/usr/share/examples/ca/openssl.conf
/usr/share/examples/ca/run.sh
/usr/share/examples/ca/turn_client_cert.pem
/usr/share/examples/ca/turn_client_pkey.pem
/usr/share/examples/ca/turn_server_cert.pem
/usr/share/examples/ca/turn_server_pkey.pem
/usr/share/examples/cpu-mem.sh
/usr/share/examples/etc/cacert.pem
/usr/share/examples/etc/coturn.service
/usr/share/examples/etc/turn_client_cert.pem
/usr/share/examples/etc/turn_client_pkey.pem
/usr/share/examples/etc/turn_server_cert.pem
/usr/share/examples/etc/turn_server_pkey.pem
/usr/share/examples/etc/turnserver.conf
/usr/share/examples/run_all_clients.sh
/usr/share/examples/run_tests.sh
/usr/share/examples/scripts/basic/dos_attack.sh
/usr/share/examples/scripts/basic/relay.sh
/usr/share/examples/scripts/basic/tcp_client.sh
/usr/share/examples/scripts/basic/tcp_client_c2c_tcp_relay.sh
/usr/share/examples/scripts/basic/udp_c2c_client.sh
/usr/share/examples/scripts/basic/udp_client.sh
/usr/share/examples/scripts/loadbalance/master_relay.sh
/usr/share/examples/scripts/loadbalance/slave_relay_1.sh
/usr/share/examples/scripts/loadbalance/slave_relay_2.sh
/usr/share/examples/scripts/loadbalance/tcp_c2c_tcp_relay.sh
/usr/share/examples/scripts/loadbalance/udp_c2c.sh
/usr/share/examples/scripts/longtermsecure/secure_dos_attack.sh
/usr/share/examples/scripts/longtermsecure/secure_dtls_client.sh
/usr/share/examples/scripts/longtermsecure/secure_dtls_client_cert.sh
/usr/share/examples/scripts/longtermsecure/secure_relay.sh
/usr/share/examples/scripts/longtermsecure/secure_relay_cert.sh
/usr/share/examples/scripts/longtermsecure/secure_sctp_client.sh
/usr/share/examples/scripts/longtermsecure/secure_tcp_client.sh
/usr/share/examples/scripts/longtermsecure/secure_tcp_client_c2c_tcp_relay.sh
/usr/share/examples/scripts/longtermsecure/secure_tls_client.sh
/usr/share/examples/scripts/longtermsecure/secure_tls_client_c2c_tcp_relay.sh
/usr/share/examples/scripts/longtermsecure/secure_tls_client_cert.sh
/usr/share/examples/scripts/longtermsecure/secure_udp_c2c.sh
/usr/share/examples/scripts/longtermsecure/secure_udp_client.sh
/usr/share/examples/scripts/longtermsecuredb/secure_relay_with_db_mongo.sh
/usr/share/examples/scripts/longtermsecuredb/secure_relay_with_db_mysql.sh
/usr/share/examples/scripts/longtermsecuredb/secure_relay_with_db_mysql_ssl.sh
/usr/share/examples/scripts/longtermsecuredb/secure_relay_with_db_psql.sh
/usr/share/examples/scripts/longtermsecuredb/secure_relay_with_db_redis.sh
/usr/share/examples/scripts/longtermsecuredb/secure_relay_with_db_sqlite.sh
/usr/share/examples/scripts/mobile/mobile_dtls_client.sh
/usr/share/examples/scripts/mobile/mobile_relay.sh
/usr/share/examples/scripts/mobile/mobile_tcp_client.sh
/usr/share/examples/scripts/mobile/mobile_tls_client_c2c_tcp_relay.sh
/usr/share/examples/scripts/mobile/mobile_udp_client.sh
/usr/share/examples/scripts/oauth.sh
/usr/share/examples/scripts/pack.sh
/usr/share/examples/scripts/peer.sh
/usr/share/examples/scripts/readme.txt
/usr/share/examples/scripts/restapi/secure_relay_secret.sh
/usr/share/examples/scripts/restapi/secure_relay_secret_with_db_mongo.sh
/usr/share/examples/scripts/restapi/secure_relay_secret_with_db_mysql.sh
/usr/share/examples/scripts/restapi/secure_relay_secret_with_db_psql.sh
/usr/share/examples/scripts/restapi/secure_relay_secret_with_db_redis.sh
/usr/share/examples/scripts/restapi/secure_relay_secret_with_db_sqlite.sh
/usr/share/examples/scripts/restapi/secure_udp_client_with_secret.sh
/usr/share/examples/scripts/restapi/shared_secret_maintainer.pl
/usr/share/examples/scripts/rfc5769.sh
/usr/share/examples/scripts/selfloadbalance/secure_dos_attack.sh
/usr/share/examples/scripts/selfloadbalance/secure_relay.sh
/usr/share/examples/var/db/turndb
/usr/share/turnserver/schema.mongo.sh
/usr/share/turnserver/schema.sql
/usr/share/turnserver/schema.stats.redis
/usr/share/turnserver/schema.userdb.redis
/usr/share/turnserver/testmongosetup.sh
/usr/share/turnserver/testredisdbsetup.sh
/usr/share/turnserver/testsqldbsetup.sql

%files dev
%defattr(-,root,root,-)
/usr/include/turn/apputils.h
/usr/include/turn/client/TurnMsgLib.h
/usr/include/turn/client/ns_turn_defs.h
/usr/include/turn/client/ns_turn_ioaddr.h
/usr/include/turn/client/ns_turn_msg.h
/usr/include/turn/client/ns_turn_msg_addr.h
/usr/include/turn/client/ns_turn_msg_defs.h
/usr/include/turn/client/ns_turn_msg_defs_experimental.h
/usr/include/turn/ns_turn_openssl.h
/usr/include/turn/ns_turn_utils.h
/usr/include/turn/server/ns_turn_allocation.h
/usr/include/turn/server/ns_turn_ioalib.h
/usr/include/turn/server/ns_turn_khash.h
/usr/include/turn/server/ns_turn_maps.h
/usr/include/turn/server/ns_turn_maps_rtcp.h
/usr/include/turn/server/ns_turn_server.h
/usr/include/turn/server/ns_turn_session.h
/usr/include/turn/stun_buffer.h
/usr/lib64/cmake/coturn/coturnConfig.cmake
/usr/lib64/cmake/coturn/turn_serverConfig-relwithdebinfo.cmake
/usr/lib64/cmake/coturn/turn_serverConfig.cmake
/usr/lib64/cmake/coturn/turn_serverConfigVersion.cmake
/usr/lib64/cmake/coturn/turnclientConfig-relwithdebinfo.cmake
/usr/lib64/cmake/coturn/turnclientConfig.cmake
/usr/lib64/cmake/coturn/turnclientConfigVersion.cmake
/usr/lib64/cmake/coturn/turncommonConfig-relwithdebinfo.cmake
/usr/lib64/cmake/coturn/turncommonConfig.cmake
/usr/lib64/cmake/coturn/turncommonConfigVersion.cmake

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/turnserver/INSTALL
/usr/share/doc/turnserver/LICENSE
/usr/share/doc/turnserver/README.turnadmin
/usr/share/doc/turnserver/README.turnserver
/usr/share/doc/turnserver/README.turnutils
/usr/share/doc/turnserver/postinstall.txt
/usr/share/doc/turnserver/schema.mongo.sh
/usr/share/doc/turnserver/schema.sql
/usr/share/doc/turnserver/schema.stats.redis
/usr/share/doc/turnserver/schema.userdb.redis
/usr/share/doc/turnserver/testmongosetup.sh
/usr/share/doc/turnserver/testredisdbsetup.sh
/usr/share/doc/turnserver/testsqldbsetup.sql

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/coturn/44edc3a7a30e912f10454aee90d312a5d0d7fa24

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/coturn.1
/usr/share/man/man1/turnadmin.1
/usr/share/man/man1/turnserver.1
/usr/share/man/man1/turnutils.1
/usr/share/man/man1/turnutils_natdiscovery.1
/usr/share/man/man1/turnutils_oauth.1
/usr/share/man/man1/turnutils_peer.1
/usr/share/man/man1/turnutils_stunclient.1
/usr/share/man/man1/turnutils_uclient.1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/turnserver.service
